export const ErrorsMap = {
  REQUIRED: 'REQUIRED',
  LENGTH: 'LENGTH',
  UNIQUE: 'UNIQUE',
  INVALID_EMAIL: 'INVALID_EMAIL',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND'
};
