version: '3.1'

services:
  nodeapp:
    build:
      dockerfile: ./Dockerfile.prod
      context: .
    ports:
      - 80:3000
    env_file: .env
    depends_on:
      - mariadb
    links:
      - mariadb
    networks:
      - network

  mariadb:
    image: mariadb:10.4
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mariadb_data:
    external: true
